title: Ian Tong Fong's Homepage
page-top-title: Ian Tong Fong
top-section-bg-text: Journalism and Communication
home-subtitle: Ian Tong Fong&ensp;|&ensp;馮恩桐
copyright-text: '&copy; Ian Tong Fong 2025. All Rights Reserved.'
